# Note: If you want to tackle fixing some of these it would be greatly appreciated

Lint/FormatParameterMismatch:
  Exclude:
    - 'test/lvm/unittests/mock.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'examples/update_by_altdisk.rb'
    - 'examples/update_by_multibos.rb'
    - 'libraries/patch_mgmt.rb'

Lint/UselessAssignment:
  Exclude:
    - 'resources/nimclient.rb'

Metrics/BlockNesting:
  Max: 4

Metrics/ParameterLists:
  Max: 6

Naming/AccessorMethodName:
  Exclude:
    - 'libraries/patch_mgmt.rb'
    - 'libraries/storage_objects.rb'
    - 'providers/altdisk.rb'
    - 'test/lvm/unittests/mock.rb'

Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'test/lvm/unittests/tc_aix_storage_objects.rb'
    - 'test/lvm/unittests/tc_storage_objects.rb'

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'resources/nimclient.rb'

Style/For:
  Exclude:
    - 'libraries/lvmobj_vg.rb'
    - 'libraries/storage_objects.rb'
    - 'test/lvm/unittests/mock.rb'

Style/IfInsideElse:
  Exclude:
    - 'libraries/storage_objects.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'libraries/lvmobj_fs.rb'
    - 'libraries/lvmobj_lv.rb'
    - 'libraries/lvmobj_vg.rb'
    - 'libraries/patch_mgmt.rb'
    - 'providers/altdisk.rb'
    - 'providers/bootlist.rb'
    - 'providers/multibos.rb'
    - 'providers/subsystem.rb'
    - 'resources/chdev.rb'
    - 'resources/inittab.rb'
    - 'resources/nimclient.rb'
    - 'resources/nimviosupdate.rb'
    - 'resources/no.rb'
    - 'resources/tunables.rb'
    - 'test/lvm/unittests/mock.rb'

Style/NonNilCheck:
  Exclude:
    - 'test/lvm/unittests/ts_all.rb'

Metrics/LineLength:
  Max: 242
