# Note: If you want to tackle fixing some of these it would be greatly appreciated

Lint/FormatParameterMismatch:
  Exclude:
    - 'test/lvm/unittests/mock.rb'

Lint/UselessAssignment:
  Exclude:
    - 'resources/nimclient.rb'

Metrics/BlockNesting:
  Max: 5

Metrics/ParameterLists:
  Max: 6

Style/AccessorMethodName:
  Exclude:
    - 'libraries/storage_objects.rb'
    - 'libraries/patch_mgmt.rb'
    - 'providers/altdisk.rb'
    - 'test/lvm/unittests/mock.rb'

Style/ClassAndModuleCamelCase:
  Exclude:
    - 'test/lvm/unittests/tc_aix_storage_objects.rb'
    - 'test/lvm/unittests/tc_storage_objects.rb'

Style/For:
  Exclude:
    - 'libraries/lvmobj_vg.rb'
    - 'libraries/storage_objects.rb'
    - 'test/lvm/unittests/mock.rb'

Style/GuardClause:
  Exclude:
    - 'libraries/lvmobj_fs.rb'
    - 'libraries/storage_objects.rb'
    - 'libraries/tools.rb'
    - 'providers/altdisk.rb'
    - 'providers/etchosts.rb'
    - 'resources/chdev.rb'
    - 'resources/chsec.rb'
    - 'resources/nimclient.rb'
    - 'resources/no.rb'
    - 'resources/nimviosupdate.rb'

Style/IdenticalConditionalBranches:
  Exclude:
    - 'providers/etchosts.rb'

Style/IfInsideElse:
  Exclude:
    - 'libraries/storage_objects.rb'

Style/Next:
  Exclude:
    - 'libraries/patch_mgmt.rb'
    - 'resources/nimviosupdate.rb'

# Cop supports --auto-correct.
# Configuration parameters: IncludeSemanticChanges.
Style/NonNilCheck:
  Exclude:
    - 'test/lvm/unittests/ts_all.rb'

Style/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'resources/nimclient.rb'
